---
apiVersion: v1
kind: Template
metadata:
  name: quayio-update-ro-keys-job
parameters:
- name: DB_HOST_SECRET
  value: ""
  required: true
- name: QUAY_APP_CONFIG_SECRET
  value: ""
  required: true
- name:  KEY_NAME
  value: ""
  required: false
- name:  EXPIRY_DATE
  value: ""
  required: false
- name: IMAGE
  value: "quay.io/app-sre/quayio-update-ro-keys-job"
  required: true
- name: IMAGE_TAG
  value: "latest"
  required: true
- name: ACTIVE_DEADLINE_SECONDS
  value: "600"
  required: true
- name: JOB_NAME
  value: ""
  required: true
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: quayio-update-ro-keys-${JOB_NAME}
  spec:
    template:
      metadata:
        labels:
          app: quayio-update-ro-keys-${JOB_NAME}
      spec:
        activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}
        backoffLimit: 6
        completions: 1
        parallelism: 1
        restartPolicy: Never
        volumes:
        - name: configvolume
          secret:
            secretName: ${{QUAY_APP_CONFIG_SECRET}}
        containers:
        - name: quayio-update-ro-keys-${JOB_NAME}
          image: ${IMAGE}:${IMAGE_TAG}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: ${{DB_HOST_SECRET}}
                key: db.host
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: ${{DB_HOST_SECRET}}
                key: db.user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${{DB_HOST_SECRET}}
                key: db.password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: ${{DB_HOST_SECRET}}
                key: db.name
          - name: KEY_NAME
            value: ${KEY_NAME}
          - name: EXPIRY_DATE
            value: ${EXPIRY_DATE}
          volumeMounts:
          - name: configvolume
            mountPath: /conf/stack

